### ISSUE TITLE
json.ex レビュー

### ISSUE THREAD

**Issue by TORIFUKUKaiou** [data-maestro/smallex#19]
# リビジョン
- bd01dff523c6b1cff16ee9dcd5d76feeb0891aca

レビューしました。
ご確認のうえ、必要なものは修正をお願いします。

①https://github.com/piacerex/smallex/blob/bd01dff523c6b1cff16ee9dcd5d76feeb0891aca/lib/json.ex#L195-L199

```elixir
def patch(domain, path, body, header) do
  patch_raw_response(domain, path, body, header)
  |> parse
end
```
関数の中身は上記のほうがよいようにおもいます。
上記のようにできなかった理由などありますでしょうか。

②https://github.com/piacerex/smallex/blob/bd01dff523c6b1cff16ee9dcd5d76feeb0891aca/lib/json.ex#L216-L219

```elixir
def delete(domain, path, header \\ []) do
  delete_raw_response(domain, path, header)
  |> parse
end
```
関数の中身は上記のほうがよい気がしています。
上記のようにできなかった理由などありますでしょうか。

③headerのデフォルトの値は、["Content-Type": "application/json"]とするのはいかがでしょうか。
- JSONのHTTP通信に特化しているから、Smallexを使う側に毎回指定させるのもどうなんだろうとおもいました
- ただPOSTやPUT、PATCH、DELETEは最低限下記のような設定が必要なことがおおいので微妙かもしれません
- Smallexを使う側が指定したheaderに`"Content-Type": "application/json"`をSmallexでマージしてしまうことも案としては考えられます
- しかしながら、気を利かせすぎのような気がして悩ましいところです

```
[
  Authorization: "Bearer token-secret",
  Accept: "Application/json; Charset=utf-8",
  "Content-Type": "application/json"
]
```

- https://github.com/piacerex/smallex/blob/bd01dff523c6b1cff16ee9dcd5d76feeb0891aca/lib/json.ex#L16
- https://github.com/piacerex/smallex/blob/bd01dff523c6b1cff16ee9dcd5d76feeb0891aca/lib/json.ex#L54
- https://github.com/piacerex/smallex/blob/bd01dff523c6b1cff16ee9dcd5d76feeb0891aca/lib/json.ex#L70
- https://github.com/piacerex/smallex/blob/bd01dff523c6b1cff16ee9dcd5d76feeb0891aca/lib/json.ex#L111
- https://github.com/piacerex/smallex/blob/bd01dff523c6b1cff16ee9dcd5d76feeb0891aca/lib/json.ex#L127
- https://github.com/piacerex/smallex/blob/bd01dff523c6b1cff16ee9dcd5d76feeb0891aca/lib/json.ex#L168
- https://github.com/piacerex/smallex/blob/bd01dff523c6b1cff16ee9dcd5d76feeb0891aca/lib/json.ex#L184
- https://github.com/piacerex/smallex/blob/bd01dff523c6b1cff16ee9dcd5d76feeb0891aca/lib/json.ex#L211
- https://github.com/piacerex/smallex/blob/bd01dff523c6b1cff16ee9dcd5d76feeb0891aca/lib/json.ex#L228

**Comment by 44103** [comment]
以下３点修正しました。
- patch関数の修正
- delete関数の修正
- headerのデフォルト引数を"Content-Type": "application/json"に変更
