### ISSUE TITLE
from esuna2 review result

### ISSUE THREAD

**Issue by TORIFUKUKaiou** [data-maestro/smallex#26]
## コメント箇所は不要なのであれば消してよいとおもいます
- https://github.com/piacerex/smallex/commit/f19cbb33911074020e173c866c795ebb3abbdfaa#diff-8e396029bd01078f5841eda805688fc0306604fc7d73a70e3931e139588ea2e6R158
- https://github.com/piacerex/smallex/commit/f19cbb33911074020e173c866c795ebb3abbdfaa#diff-8e396029bd01078f5841eda805688fc0306604fc7d73a70e3931e139588ea2e6R166-R168

## TODOは別途解決する必要がありそうです
- https://github.com/piacerex/smallex/commit/f19cbb33911074020e173c866c795ebb3abbdfaa#diff-8e396029bd01078f5841eda805688fc0306604fc7d73a70e3931e139588ea2e6R189

**Comment by 44103** [comment]
### コメントの消去
全く異論ありません。piacereさんさえよろしければ、消去してしまいたいと思います。

### TODOの解決
挙げてくださったとおり、こちらは、必要に応じて別途Issueに挙げさせていただいた方が良いかもしれません。

**Comment by 44103** [comment]
コメント箇所はコメントを外して対処しています。
