### ISSUE TITLE
from_dataframex review result

### ISSUE THREAD

**Issue by TORIFUKUKaiou** [data-maestro/smallex#27]
## Enum.filter(&(&1 != nil))
https://github.com/piacerex/smallex/blob/48f7fa8ade46382a485367d7e458b182f8b41ca8/lib/type.ex#L249
好みの問題かもしれませんが
Enum.reject(&(&1 == nil))
のほうが私はわかりやすいです。

## Enum.frequencies/1
https://github.com/piacerex/smallex/blob/48f7fa8ade46382a485367d7e458b182f8b41ca8/lib/lst.ex#L62
は
[Enum.html#frequencies/1](https://hexdocs.pm/elixir/Enum.html#frequencies/1)が使えます。
ただしelixirのバージョンは1.10以上
smallexは、現状は1.6以上としています。
https://github.com/piacerex/smallex/blob/48f7fa8ade46382a485367d7e458b182f8b41ca8/mix.exs#L8
変えるのならpiacere さんに相談の上、サポートバージョン自体かえてしまう処置が必要です。

**Comment by 44103** [comment]
### Enum.filter(&(&1 != nil))
filterはどの言語にも大体あるので知っていましたが、 `Enum.reject` という表記もあることは知りませんでした。勉強になります。修正することに異論はありません。

### Let.frequency/1
こちらは、グローバルでElixirの使用されているメジャーバージョンが1.10以上でしたら、置き換えても良いかと思いますが、様々なバージョンが幅広く使われている可能性が高いのであれば、あえて残しておいた方が良いと思いました。

**Comment by digi-dock** [comment]
@44103 どちらも必須では無いので、そのままが希望です（特に、filterとrejectの使い分けは、Elixirらしく無いかなぁ？）

**Comment by 44103** [comment]
@digi-dock @TORIFUKUKaiou ひとまず、頂いた内容の通り変更しない方針を考えています。
