### ISSUE TITLE
from_ddacademy.tech review result

### ISSUE THREAD

**Issue by TORIFUKUKaiou** [data-maestro/smallex#28]
from_ddacademy.tech
from_digi-dock.com
from_neos_real
from_sphere/to_merge_smallex
from_web_socket_chat
from_web_socket_digi-dock
-> これらは差分の内容が同じであることを確認しました。
そのためfrom_ddacademy.techとの比較結果を代表して書いておきます。

## Dt.to_ymdhmsl/1
https://github.com/piacerex/smallex/blob/48f7fa8ade46382a485367d7e458b182f8b41ca8/lib/dt.ex#L54
from_ddacademy.techのほうとは%Lのところに差がありますがv1.0ブランチの内容のほうを採用した理由はなにでしょうか。

- https://elixir-di.slack.com/archives/C01NWN6EZ5K/p1615745469208200
- この話でしょうか

## Lst.match/2 => マージしないことを認識しました(torifuku)
Lst.matchをマージしていない理由はなにでしょうか。
=> https://elixir-di.slack.com/archives/C01NWN6EZ5K/p1615564065199300
=> Lst.matchが、Enum.any?と大差無い（関数指定が値指定になるだけ）ので、削除しました
- この話のことですね

**Comment by 44103** [comment]
### Dt.to_ymdhmsl/1
> from_ddacademy.techのほうとは%Lのところに差がありますがv1.0ブランチの内容のほうを採用した理由はなにでしょうか。

添付していただいたSlackの内容の通り、 `"%Y/%0m/%0d %0H:%0M:%0S.%0L"` としているとテストコードの秒数以下6桁のテストコードが走らなかったため、piacereさんに `"%Y/%0m/%0d %0H:%0M:%0S.%L"` とさせていただきました。

### Lst.match/2
> Lst.matchをマージしていない理由はなにでしょうか。

こちらも添付していただいた通り、piacereさんに削除していただきました。

**Comment by TORIFUKUKaiou** [comment]
ご確認ありがとうございます。
クローズします。
