### ISSUE TITLE
Smallexモジュール

### ISSUE THREAD

**Issue by TORIFUKUKaiou** [data-maestro/smallex#9]
旧バージョンと互換性はなくなりますが

Smallex.Dt (lib/smallex/dt.ex)
Smallex.Excel (lib/smallex/excel.ex)
Smallex.Fl (lib/smallex/fl.ex)
...
Smallex.Type (lib/smallex/type.ex)

というようにSmallexのモジュールの下に配置しなおしたほうがよいかもしれません。

- 私はSmallexモジュールの下に置く方を推します
- Smallexモジュール名を覚えておけばよい
  - たとえばVSCodeでElixirのプラグインを入れていると、SmallexとタイプしたところでSmallexがもっているモジュールの候補がでてきます
  - Smallexまで覚えていればあれだよ、あれと探しやすくなる気がしています
- Smallex.Xxxとすることでモジュール名がかぶることがなくなる(Number、Type、Json等こういう名前のものがいつかElixir本体の中にでてきても問題がないと考えています)

**Comment by TORIFUKUKaiou** [comment]
@piacerex さん、ご意見いただけますでしょうか。

**Comment by piacerex** [comment]
悩ましい…できるだけタイプ数を減らしたい（かつフォルダも掘りたくない）というところからSmallexはスタートしてたので…

本当は、LstやSlは、標準モジュール（ListモジュールやFileモジュール）の拡張とかにしたい位で、defimplで拡張したい位なんですよねー

**Comment by TORIFUKUKaiou** [comment]
ご確認ありがとうございます。
考えても答えはでそうにないのですがいきなり閉じてしまうのもアレなのでもう少し考えてみます。
(という体でしばらくそのままにしておきます。どなたかが意見を行ってくれることを期待して)

繰り返しですが、ただ考えても答えはでそうにないのでいまのところpiacerexさんの意見に賛同するということになると思います。
(Smallex.Xxxという形でしかHex登録できないとかそんな制約は未来においてもないでしょうし)

**Comment by TORIFUKUKaiou** [comment]
正式リリース間近であり、議論のためのIssueなので閉じる。
